name: Generate Tetris GIF

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-tetris:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          

      - name: Install Dependencies
        run: |
          pip install -r tetris/requirements.txt
          
      - name: Create dist directory
        run: mkdir dist

      - name: Generate GIF
        run: |
          python tetris/main.py --username abisinraj --theme light --output github-contribution-grid-tetris.gif
          python tetris/main.py --username abisinraj --theme dark --output github-contribution-grid-tetris-dark.gif
        
      - name: Push new image to output branch
        run: |
          mkdir -p ../dist
          mv github-contribution-grid-tetris.gif ../dist/
          mv github-contribution-grid-tetris-dark.gif ../dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output-tetris
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
